#!/usr/bin/bash
dirsearch="$(find . -maxdepth 1 -type d -not -name '.*')"

function topicSearch() {
    cd $1 > /dev/null
    find . -maxdepth 1 -type f -not -name 'index.adoc' -name '*.adoc'
    cd - > /dev/null
}

for dir in $dirsearch; do
     for adoc in $(topicSearch $dir); do
         file=$(echo "$adoc" | cut -c 3-)
         echo ${file%.*}
    done
done

