#!/usr/bin/bash
echo "creating indices..."
dirsearch="$(find . -maxdepth 1 -type d -not -name '.*')"

function topicSearch() {
    find . -maxdepth 1 -type f -not -name 'index.adoc' -name '*.adoc'
}

for dir in $dirsearch; do
    cd $dir > /dev/null

    topic=$(echo ${dir} | cut -c 3-)
    rm -rf index.adoc
         echo \
"= $dir
:docinfo: shared
:source-highlighter: pygments
:pygments-style: monokai
:icons: font
:stem:
:toc: left
:docinfodir: ..

== Topics
" > index.adoc

     for adoc in $(topicSearch); do
        file=$(echo "$adoc" | cut -c 3-)
        subTopic=${file%.*}
        # echo $subTopic
        echo "* https://raw.githack.com/A-Larsen/math-notes/refs/heads/main/${topic}/${subTopic}.html[${subTopic}]" >> index.adoc
        #  # echo $subTopic

    done

    cd - > /dev/null
done

