#!/usr/bin/bash
dirsearch="$(find . -maxdepth 1 -type d -not -name '.*')"

function topicSearch() {
    find . -maxdepth 1 -type f -not -name 'index.adoc' -name '*.adoc'
}

for dir in $dirsearch; do
    cd $dir > /dev/null

         echo \
"= $dir
:docinfo: shared
:source-highlighter: pygments
:pygments-style: monokai
:icons: font
:stem:
:toc: left
:docinfodir: ..
" > index.html

     for adoc in $(topicSearch); do
        file=$(echo "$adoc" | cut -c 3-)
        topic=${file%.*}
        echo "== Topics" >> index.html
        echo "* https://raw.githack.com/A-Larsen/math-notes/refs/heads/main/Algrebra/${topic}.html[${topic}]" >> index.html
         # echo $topic

    done

    cd - > /dev/null
done

